BOT_TOKEN = 'YOUR-BOT-TOKEN'
DEBUG_MODE = True
CAPTAIN_PASSWORD = '1234098756'
ADMIN_PASSWORD = '1234098756'
QUESTION_TIME_LIMIT = 5    # в минутах
FIRST_CLUE_OF_QUESTION = 1    # в минутах
SECOND_CLUE_OF_QUESTION = 3    # в минутах
THIRD_CLUE_OF_QUESTION = 4   # в минутах
