BOT_TOKEN = '7928066551:AAEqGRKKAdWHo0MswWNTUAE9Q7B9OTN63-I'
DEBUG_MODE = True
CAPTAIN_PASSWORD = '1234'
ADMIN_PASSWORD = '12345'
QUESTION_TIME_LIMIT = 5    # в минутах
FIRST_CLUE_OF_QUESTION = 1    # в минутах
SECOND_CLUE_OF_QUESTION = 3    # в минутах
THIRD_CLUE_OF_QUESTION = 4    # в минутах
